#!/bin/zsh

########################
# Aliases for commands #
########################

alias rmm=rrm # An old alias I used to use and might do on accident

alias t=trash # Shorthand to make sure I use it more.
alias '%= ' '$= ' # Make sure an `%`/`$` at the beginning of a line will be ignored.


alias s=subl
alias ss=ssubl


#### !!!!
# You can alias variablessssss to be function calls
