#!/bin/zsh

#################################################################################
# Options relating to the file system -- listing, creating, changing files/dirs #
#################################################################################

## Listing files
alias ls='ls -AhGb' # Always print out `.` files, and for longform, human-readable sizes, and colours
alias ll='ls -l'   # Shorthand for `ls -al`

## Creating files
alias touchd='mkdir -p' # alias incase i ever end up using it

function ttouch () for file; do  # Same as `touch`, except it will create directories as needed.
	mkdir -p $file:h && touch $file
done

## Creating Folders (& cding to them)
function mkdircd () { mkdir -p $@ && cd $@ }
alias cdmkdir=mkdircd
alias cdm=mkdircd
function mkd () mkdir -p $@
function mkf () { mkdir -p ${@:h} && command touch $@ }

## Symlinks
function symlink () {
	ln -s ${1?need existing file name} ${2?need name of destination}
}

## Deleting files
alias purge='command rm -riP' ## Purge deletes something entirely
alias ppurge='command rm -rfP'
