#!/bin/zsh

alias grep='grep --color=auto'

# Same as `source`, except only does it if the file exists.
function source-optional () {
	for file; do
		[[ -e $file ]] && source $file
	done
}

# Same as `source`, except warns if it doesn't exist.
function source-or-warn () {
	for file; do
		if [[ -e $file ]]; then
			source $file
		else
			echo "[warn] Unable to source file: $file" >&2
		fi
	done
}
return
