#!/bin/zsh

# Prints out how many arguments were passed; used in testing expansion syntax.
function nargs () echo $#

# I frequently use this.
export words=/usr/share/dict/words

alias grep='grep --color=auto'

function reload reload-samp-shell () {
	source $samp_shell_shared_home/${1:-.zshrc}
	echo "Reloaded $_"
}
