#!/bin/zsh

# Prints out how many arguments were passed; used in testing expansion syntax.
function nargs () echo $#

# I frequently use this.
export words=/usr/share/dict/words

if false; then
	# Gets the current branch (ISH---this isn't working)
	function git-current-branch () git rev-parse --abbrev-ref HEAD

	# Returns zero or nonzero depending on when on if it's in a repo.
	function is-in-a-git-repo () git rev-parse --is-inside-work-tree >&- 2>&-
fi
