#!/bin/zsh

########################
# Aliases for commands #
########################

alias t=trash
alias d=dirs
alias s=subl
alias ss=ssubl

alias rmm=rrm # An old alias I used to use and might do on accident

alias '%= ' '$= ' # Make sure an `%`/`$` at the beginning of a line will be ignored.


## Spellcheck
alias gti=git
alias sbul=subl
alias ssbul=ssubl

## under-used, but still want them
alias pwc='current-commit'
alias pwb='current-branch'
alias mbr='master-branch'
