#!/bin/zsh

# Prints out how many arguments were passed; used in testing expansion syntax.
function nargs () {
	echo $#
}

# I frequently use this.
export SAMP_SHELL_WORDS=${SAMP_SHELL_WORDS:-/usr/share/dict/words}
[[ -v words ]] || export words=$SAMP_SHELL_WORDS

alias grep='grep --color=auto'

function reload-samp-shell () {
	local file_to_reload=$SAMP_SHELL_HOME/${1:-.zshrc}
	source $file_to_reload
	echo "Reloaded $file_to_reload"
}
does-function-exist reload || alias reload=reload-samp-shell

alias clean-zsh='env -i =zsh -f'

# Same as `source`, except only does it if the file exists.
function source-optional () for file; do
	[[ -e $file ]] && source $file
done

# Same as `source`, except warns if it doesn't exist.
function source-or-warn () for file; do
	if [[ -e $file ]]; then
		source $file
	else
		warn "Unable to source file: $file"
	fi
done
