#!/bin/zsh

local root=${_samp_shell_root?missing root folder}
local zshdotdir=${ZSHDOTDIR:-$HOME}

cat <<EOS >> $zshdotdir/.zshenv
# Setup sampshell zshenv
[[ -e \${_samp_shell_root:-${(Q)root}}/.zshenv ]] && source \${_samp_shell_root:-${(Q)root}}/.zshenv
EOS

cat <<EOS >> $zshdotdir/.zshrc
# Setup sampshell zshrc
[[ -e \${_samp_shell_root:-${(Q)root}}/.zshrc ]] && source \${_samp_shell_root:-${(Q)root}}/.zshrc
EOS
